apiVersion: v1 
kind: Service 
metadata:
  name: zk-svc
  namespace: geode-ap136976-dev-aks
spec:
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper-uat
---
apiVersion: v1 
kind: Service 
metadata:
  name: kafka-svc
  namespace: geode-ap136976-dev-aks
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka-uat
